manga_base/accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'

urlpatterns = [
  path('register', views.register, name='register'),
  path('my-login', views.my_login, name="my-login"),
  path('user-logout', views.user_logout, name='user-logout')
]

manga_base/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
  path('', views.home, name='home'),
  path('my-profile', views.profile, name='profile'),
  path('my-profile/change-password', views.change_password, name='change-password')
]

manga_base/manga/urls.py
from django.contrib import admin
from django.urls import path, include

from manga import settings 
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls', namespace='main')),
    path("manga/", include('read.urls', namespace='read')),
    path('authentication/', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
  urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls"))
    ]
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manga_base/read/urls.py
from django.urls import path
from . import views

app_name = 'read'

urlpatterns = [
  path('<slug:manga_slug>/', views.read, name='read_manga')
]

manga_base/accounts/models.py
from django.db import models

manga_base/read/models.py
from django.db import models

# Create your models here.

class Categories(models.Model):
  name = models.CharField(max_length=150, verbose_name='Name')
  slug = models.SlugField(max_length=200, blank=True, null=True, verbose_name='URL')

  class Meta:
    db_table = 'category'
    verbose_name = 'Category'
    verbose_name_plural = 'Categories'

  def __str__(self) -> str:
    return self.name

class Types(models.Model):
  type = models.CharField(max_length=150)

  def __str__(self) -> str:
    return self.type

  
class Manga(models.Model):
  name = models.CharField(max_length=150, unique=True, verbose_name='Name')
  name_in_jap = models.CharField(max_length=150, unique=True, verbose_name='Name_in_jap')

  categories = models.ManyToManyField(Types)

  description = models.TextField(blank=True, null=True, verbose_name='Desciption')
  category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Type')
  status = models.CharField(max_length=150, verbose_name='Status')
  author = models.TextField(blank=True, null=True, verbose_name='Author')
  magazine = models.TextField(blank=True, null=True, verbose_name='Magazine')
  published = models.TextField(blank=True, null=True, verbose_name='Publish_Date')
  score = models.DecimalField(default=0.00, max_digits=4 ,decimal_places=2)
  views = models.DecimalField(default=0.00, max_digits=100, decimal_places=0)
  image = models.ImageField(upload_to='manga_images', blank=True,  null=True)
  slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

  number_of_chapters = models.DecimalField(default=0.00, max_digits=5 ,decimal_places=0, verbose_name="Number of Chapters")

  class Meta:
    db_table = 'Manga'
    verbose_name = 'Manga'
    verbose_name_plural = 'Mangas'

  def __str__(self) -> str:
    return self.name
  

manga_base/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from django import forms 

from django.forms.widgets import PasswordInput, TextInput

class CreateUserForm(UserCreationForm):

  class Meta:

    model = User
    fields = ['username', 'email']
    

class LoginForm(AuthenticationForm):
  
  username = forms.CharField(widget=TextInput())
  password = forms.CharField(widget=PasswordInput())

manga_base/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from accounts.forms import CreateUserForm, LoginForm
# Create your views here.
from django.contrib.auth.models import auth
from django.contrib.auth import authenticate, login, logout


def register(request):

  form = CreateUserForm()

  if request.method == 'POST':
    form = CreateUserForm(request.POST)

    if form.is_valid():
      form.save()
      return redirect('my-login')
    
  context = {'registerform': form}
  
  return render(request, 'accounts/register.html', context)




def my_login(request):
  form = LoginForm()

  if request.method == 'POST':
    form = LoginForm(request, data=request.POST)

    if form.is_valid():

      username = request.POST.get('username')
      password = request.POST.get('password')

      user = authenticate(request, username=username, password=password)

      if user is not None:
        auth.login(request, user)

        return redirect('/')
      
  context = {'loginform': form}
  return render(request, 'accounts/my-login.html', context)

def user_logout(request):

  auth.logout (request)
  return redirect('/')

manga_base/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.

from read.models import Manga


def home(request):

  manga = Manga.objects.all()

  context = {
    'manga': manga
  }

  return render(request, "main/index.html", context)

def profile(request):

  username = request.user.username
  
  context = {
    'user_name': username
  }

  return render(request, 'main/profile.html', context)

def change_password(request):

  if request.method == 'POST':
    
    form = PasswordChangeForm(request.user, request.POST)

    if form.is_valid():
      user = form.save()
      update_session_auth_hash(request, user)
      messages.success(request, 'Your password was successfully updated!')
      return redirect('change_password')
    else:
      messages.error(request, 'Please correct the error below.')
  else:
    form = PasswordChangeForm(request.user)

  context = {
    'form': form
  }

  return render(request, 'accounts/change_password.html', context)

manga_base/read/views.py
from django.shortcuts import render

# Create your views here.
from read.models import Manga

def read(request, manga_slug):
  manga = Manga.objects.get(slug=manga_slug)

  chapters = []
  for i in range(int(manga.number_of_chapters)):
    chapters.append(i)
  context = {
    'manga': manga,
    'chapters': chapters
  }
  
  return render(request, 'read/index.html', context)

manga_base/accounts/templates/accounts/change_password.html
{% extends "main/base.html" %} {% load static %} 


{% block css_main %}

{% endblock %}

{% block content %}

<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

{% endblock %}

manga_base/accounts/templates/accounts/my-login.html
{% extends "main/base.html" %} {% load static %} 


{% block css_main %}

{% endblock %}

{% block content %}


<form method='POST'>
  {% csrf_token %}

  <h1 class="text-white text-center">
		Login here
	</h1>

  <div class="text-center">
    {% for field in loginform %}
    <div class="fieldWrapper text-white" style="padding-bottom: 0.2rem;">
      {{ field.errors }}
      {{ field.label_tag }} {{ field }}
      
    </div>
    {% endfor %}

    <button type="submit" value="Login" class="button btn-light">Login</button>


  </div>


</form>
{% endblock %}

manga_base/accounts/templates/accounts/register.html
{% extends "main/base.html" %} {% load static %}

{% block css_main %}
{% endblock %}

{% block content %}
<form method="POST">
	{% csrf_token %}

	<h1 class="text-white text-center">
		Register here
	</h1>
	<div class="text-center">
    {% for field in registerform %}
        <div class="fieldWrapper text-white" style="padding-bottom: 0.2rem;">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
        </div>
    {% endfor %}
	<button type="submit" value="Register" class="button btn-light">Register</button>
	</div>

</form>
{% endblock %}

manga_base/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Read Manga</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link type="text/css" href="{% static 'main/css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />
    {% block css_main %}

    {% endblock %}
  </head>



  <body class="bg-black">
    <nav
      class="navbar navbar-expand-sm bg-dark justify-content-between NavBar text-white font-weight-bold"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="{% static 'main/icons/manga_logo.jpg' %}"
            style="height: 50px"
            class="rounded"
          />
        </a>
        <ul>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              >Каталог</a
            >
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Манга</a></li>
              <li><a class="dropdown-item" href="#">Манхва</a></li>
              <li><a class="dropdown-item" href="#">Маньхуа</a></li>
              <li><a class="dropdown-item" href="#">Комиксы</a></li>
            </ul>
          </li>
        </ul>
        <div>
          <div class="collapse navbar-collapse">
            <form class="d-flex">
              <input
                class="form-control me-2"
                type="text"
                placeholder="Search"
              />
              <button class="btn btn-dark" type="button">Search</button>
            </form>
            {% if user.is_authenticated %}
              <a href="{% url 'accounts:user-logout' %}">
                <button type="button" class="btn btn-dark">Выйти</button>
              </a>

              <a href="{% url 'main:profile'%}">
                <button type="button" class="btn btn-outline-light">
                  Мой профиль
                </button>
              </a>
            {% else %}
              <a href="{% url 'accounts:my-login' %}">
                <button type="button" class="btn btn-dark" href="{% url 'accounts:my-login' %}">Вход</button>
              </a>


              <a href="{% url 'accounts:register' %}">
                <button type="button" class="btn btn-outline-light">
                  Регистрация
                </button>
              </a>
            {% endif %}


          </div>
        </div>
      </div>
    </nav>

    {% block content %}{% endblock %}

    <hr style="color: white;">

    <footer class="py-4">
      <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; b2k4rys 2024</p>
      </div>
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

manga_base/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}


{% block css_main %}
<style>
  html,
  body {
    position: relative;
    height: 100%;
    margin: 0;
    padding: 0;
  }

  .swiper {
    width: 100%;
    height: 300px; /* Adjust the height as needed */
  }

  .swiper-slide {
    text-align: center;
    font-size: 18px;
    background: #000;
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .swiper-slide img {
    display: block;
    max-width: 100%;
    max-height: 100%;
    object-fit: contain;
  }

  .card-img-top {
      height: 300px; /* Adjust the height as needed */
      width: 100%;
      object-fit: cover;
    }

  .card-spacing {
    margin-left: 20px; /* Adjust the margin as needed */
  }
</style>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
  <div>
    <h2 class="text-white font-weight-bold">Популярные Тайтлы</h2>
  </div>
</div>


<div class="swiper mySwiper">
  <div class="swiper-wrapper">
    {% for each_manga in manga %}
    <div class="swiper-slide"><a href="{% url "read:read_manga" each_manga.slug %}"><img src='{{ each_manga.image.url }}' alt="{{ each_manga.name }}"></a></div>
    {% endfor %}
    
  </div>
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
  <div class="swiper-pagination"></div>
</div>


<div class="d-flex justify-content-start">
  <div>
    <h2 class="text-white font-weight-bold" style="padding-left: 25px; padding-top: 25px;">Подборки</h2>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="d-flex">
    <div class="card bg-dark" style="width: 18rem;">
      <img src="{% static 'main/collections_covers/powerful_main.jpeg' %}" class="card-img-top">
      <div class="card-body text-white">
        <h3 class="card-title">Мощьный ГГ</h3>
        <p class="card-text">Коллекция манги с сильным гг</p>
      </div>
    </div>
  </div>

  <div class="d-flex card-spacing">
    <div class="card bg-dark" style="width: 18rem;">
      <img src="{% static 'main/collections_covers/best_manga.jpeg' %}" class="card-img-top">
      <div class="card-body text-white">
        <h3 class="card-title">Топ манги</h3>
        <p class="card-text">Лучшие манги по мнению создателя сайта</p>
      </div>
    </div>
  </div>

  <div class="d-flex card-spacing">
    <div class="card bg-dark" style="width: 18rem;">
      <img src="{% static 'main/collections_covers/anti_hero.jpeg' %}" class="card-img-top">
      <div class="card-body text-white">
        <h3 class="card-title">Анти Герой</h3>
        <p class="card-text">Каково это, противостоят всему миру?</p>
      </div>
    </div>
  </div>
</div>



<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
<script>
  var swiper = new Swiper(".mySwiper", {
    slidesPerView: 6,
    spaceBetween: 10,
    navigation: {
      nextEl: ".swiper-button-next",
      prevEl: ".swiper-button-prev",
    },
  });
</script>
{% endblock %}

manga_base/main/templates/main/profile.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}

<div class="text-center">
  <h1 class="text-white">
    My profile 
  </h1>
</div>

<div class="container text-center">
  <div class="row align-align-items-center">
    <div class='col'>
      <img src="{% static 'main/collections_covers/powerful_main.jpeg' %}" style="height: 100px;" class="rounded-circle">
    </div>

    <div class="col">
      <h2 class="text-white"> {{ user_name }}</h2>
      <h2 class="text-white"><a href="{% url 'main:change-password' %}">Change password</a></h2>
    </div>
  </div>
</div>


{% endblock %}

manga_base/read/templates/read/index.html
{% extends "main/base.html" %} {% load static %} {% block css_main %}

<style>
  .custom-btn-sm {
    padding: 0.25rem 0.5rem;
    font-size: 0.75rem;
  }

  .button-container {
    display: flex;
    flex-wrap: nowrap;
    gap: 0.5rem; /* Adjust gap as needed */
    margin-top: 1rem; /* Space between 'Read Now' and other buttons */
  }

  .mt-3 {
    margin-top: 1rem; /* Adds margin-top to the paragraph */
  }

  .col-info p {
    margin: 10px; /* Removes margin between paragraphs */
    line-height: 1.2; /* Adjusts line height to make the space between lines smaller */
  }

  .read-more-btn {
    margin-top: 0.5rem;
    color: white; /* Bootstrap info color */
    cursor: pointer;
    text-decoration: underline;
    background: none;
    border: none;
    padding: 0;
    font-size: 1.25rem; /* Same size as the paragraph text */
  }

  .chapter-button {
    margin: 5px;
  }

.chapter-container {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
  }

</style>
{% endblock %} 

{% block content %}
<div class="container content-container">
  <div class="row">
    <div class="col-12 col-md-3 col-img">
      <img
        src="{{ manga.image.url }}"
        style="height: 300px"
        class="rounded border border-light mx-auto"
      />
    </div>

    <div class="col-12 col-md-5 col-content">
      <h2 class="text-white font-weight-bold" style="white-space: nowrap">
        {{ manga.name }}
      </h2>
      <p class="text-secondary">{{ manga.name_in_jap }}</p>
      <button type="button" class="btn btn-warning font-weight-bold">
        Read Now
      </button>

      <div class="button-container">
        {% for type in manga.categories.all %}
        <button type="button" class="btn btn-dark custom-btn-sm">{{ type }}</button>
        {% endfor %}
      </div>

      <p class="mt-3 text-white">
        {{ manga.description }}
      
      </p>
      <button
        type="button"
        class="read-more-btn"
        data-toggle="modal"
        data-target="#readMoreModal"
      >
        + Read full
      </button>
    </div>

    <div class="col-12 col-md-4 col-info text-white">
      <p>Type: {{ manga.category }}</p>
      <p>Status: {{ manga.status }}</p>
      <p>Authors: {{ manga.author }}</p>
      <p>Magazines: {{ manga.magazine }}</p>
      <p>Published: {{ manga.published }}</p>
      <p>Score: {{ manga.score }}</p>
      <p>Views: {{ manga.views }}</p>
      <p>Number of chapters: {{ manga.number_of_chapters }}</p>
    </div>
  </div>
</div>

<hr style="color:white;">

<div class="container">
  <div class="chapter-container">
      {% for chapter in chapters %}
          <button type="button" class="btn btn-dark chapter-button">Chapter {{ chapter }}</button>
      {% endfor %}
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="readMoreModal"
  tabindex="-1"
  aria-labelledby="readMoreModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content bg-dark text-white">
      <div class="modal-header">
        <h5 class="modal-title" id="readMoreModalLabel">
          {{ manga.name }} Full Description
        </h5>
      </div>
      <div class="modal-body">
        {{ manga.description }}
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% endblock %}